### ISSUE TITLE
The version of TensorFlow?

### ISSUE THREAD

**Issue by zssasa** [instillai/TensorFlow-Course#23]
I want to know the version of tf in this repo.
In the 0-welcome, I use tf1.12, and the executed welcome string is bytes.
![tf_version](https://user-images.githubusercontent.com/11346619/51508320-a14d3a80-1e2f-11e9-8e61-3ffbfe589a13.png)

**Comment by astorfi** [comment]
It is compatible with the latest one.

**Comment by happypycode** [comment]
Very sorry，but this lesson is not runable using my tensorflow version 
```python
>>> import tensorflow as tf
2020-04-14 11:47:21.897440: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-14 11:47:21.909470: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.  
>>> tf.__version__
'2.2.0-rc2'
>>> test = tf.constant("foo")
>>> with tf.Session() as sess:
...     sess.run(a)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'Session'  
```
The only way to run the code is by adding `import tensorflow.compat.v1 as tf`.
```python
>>> import tensorflow.compat.v1 as tf
>>> tf.disable_v2_behavior()
WARNING:tensorflow:From C:\Users\Lenovo\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
>>> test = tf.constant("foo!")
>>> with tf.Session() as sess:
...     sess.run(test)
...
b'foo!'
```
But some code still cannot run:
```python
>>> import tensorflow.compat.v1 as tf
>>> tf.disable_v2_behavior()
WARNING:tensorflow:From C:\Users\Lenovo\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
>>> tf.contrib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'
```
I know this is because tf.contrib is deleted completely from tensorflow2. But how can I learn this lesson using tf2?
